---
apiVersion: build.knative.dev/v1alpha1
kind: Build
metadata:
  name: kaniko-build
spec:
  serviceAccountName: builder
  source:
    git:
      url: https://github.com/ddadlani/knative-test
      revision: master
  template:
    name: kaniko
    arguments:
      - name: IMAGE
        value: docker.io/ddadlani/helloworld-go
