---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: google/cloud-sdk
    tag: slim

inputs:
  - name: knative-app
  - name: app

params:
  CONFIG:
  CLUSTER_NAME:
  PROJECT_NAME:
  ZONE:

run:
  path: knative-app/ci/tasks/run-kaniko-build.sh
