---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ddadlani/kubectl
    tag: latest

inputs:
  - name: knative-app
  - name: app

params:
  CONFIG:
  CLUSTER_NAME:
  PROJECT_NAME:
  ZONE:

run:
  path: knative-app/ci/tasks/build-kaniko-image.sh
