---
platform: linux

image_resource:
    type: docker-image
    source:
      repository: ddadlani/kubectl

inputs:
  - name: knative-deployment

params:
  CONFIG:
  CLUSTER_NAME:
  PROJECT_NAME:
  ZONE:
  BUILD_NAME:

run:
  path: knative-deployment/ci/tasks/run-build.sh
