---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: google/cloud-sdk
    tag: latest


inputs:
  - name: knative-app
    - name: helloworld-go

params:

run:
  path: knative-test/ci/tasks/serve.sh
