---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ddadlani/kubectl

inputs:
  - name: knative-deployment

params:
  CONFIG:
  CLUSTER_NAME:
  PROJECT_NAME:
  ZONE:

run:
  path: knative-deployment/ci/tasks/serve.sh
