---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ddadlani/kubectl
    tag: latest


inputs:
  - name: knative-test
  - name: app

params:
  CONFIG:
  CLUSTER_NAME:
  PROJECT_NAME:
  ZONE:

run:
  path: knative-test/ci/tasks/serve.sh
