---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: google/cloud-sdk
    tag: latest


inputs:
  - name: knative-test
  - name: helloworld-go

params:
  CONFIG:
  CLUSTER_NAME:
  PROJECT_NAME:
  ZONE:

run:
  path: knative-test/ci/tasks/serve.sh
