---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: google/cloud-sdk
    tag: latest


inputs:
  - name: knative-app

params:
  CONFIG: CONFIG

run:
  path: knative-app/ci/tasks/test.sh
