---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: latest


inputs:
  - name: knative-deployment
  - name: helloworld-go

params:

run:
  path: knative-deployment/ci/tasks/test-unit.sh
