---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: latest


inputs:
  - name: knative-test
  - name: helloworld-go

params:

run:
  path: knative-test/ci/tasks/run-tests.sh
