---
resources:
- name: knative-test
  type: git
  check_every: 10s
  source: {uri: "https://github.com/ddadlani/knative-test"}
- name: helloworld-go
  type: git
  check_every: 10s
  source: {uri: "https://github.com/ddadlani/helloworld-go"}
- name: kubectl
  type: docker-image
  source: {repository: ddadlani/kubectl}

jobs:
- name: unit
  plan:
  - get: knative-test
  - get: helloworld-go
    trigger: true
  - task: test-unit
    file: knative-test/ci/tasks/test-unit.yml

- name: build-image
  plan:
  - get: knative-test
    trigger: true
  - get: helloworld-go
    passed: [unit]
    trigger: true
  - get: kubectl
  - task: build-image
    image: kubectl
    file: knative-test/ci/tasks/build-kaniko-image.yml
    params:
      CONFIG: ((key))
      CLUSTER_NAME: ((cluster))
      PROJECT_NAME: ((project))
      ZONE: ((zone))
    input_mapping:
      app: helloworld-go
  - task: watch-kaniko-build
    image: kubectl
    file: knative-test/ci/tasks/watch-kaniko-build.yml
    params:
      CONFIG: ((key))
      CLUSTER_NAME: ((cluster))
      PROJECT_NAME: ((project))
      ZONE: ((zone))
    timeout: 10m
  - task: delete-build
    image: kubectl
    config:
      platform: linux
      run:
        path: sh
        args:
        - -c
        - |
         kubectl delete build kaniko-build

# - name: kubectl
#   plan:
#   - get: knative-test
#   - task: test
#     file: knative-test/ci/tasks/test.yml
#     params:
#       CONFIG: ((key))
#       CLUSTER_NAME: ((cluster))
#       PROJECT_NAME: ((project))
#       ZONE: ((zone))
#     input_mapping: {knative-app: knative-test}
- name: serve
  plan:
  - get: knative-test
    passed: [unit]
    trigger: true
  - task: serve-hello
    file: knative-test/ci/tasks/serve.yml

