---
resources:
- name: knative-test
  type: git
  source: {uri: "https://github.com/ddadlani/knative-test"}

jobs:
- name: unit
  plan:
  - get: knative-test
    trigger: true
  - task: test
    file: knative-test/ci/tasks/test.yml
    params:
      CONFIG: ((key))
      CLUSTER_NAME: ((cluster))
    input_mapping: {knative-app: knative-test}

