---
resources:
- name: knative-test
  type: git
  check_every: 10s
  source: {uri: "https://github.com/ddadlani/knative-test"}
- name: helloworld-go
  type: git
  check_every: 10s
  source: {uri: "https://github.com/ddadlani/helloworld-go"}

jobs:
- name: unit
  plan:
  - get: knative-test
  - get: helloworld-go
    trigger: true
  - task: test-unit
    file: knative-test/ci/tasks/test-unit.yml

- name: build-image
  plan:
  - get: knative-test
    trigger: true
  - get: helloworld-go
    trigger: true
  - task: build-image
    file: knative-test/ci/tasks/build-kaniko-image.yml
    params:
      CONFIG: ((key))
      CLUSTER_NAME: ((cluster))
      PROJECT_NAME: ((project))
      ZONE: ((zone))
    input_mapping:
      knative-app: knative-test
      app: helloworld-go
  # - task: get-build-status
  #   file: knative-test/ci/tasks/get-build-status.yml
  #   params:
  #     CONFIG: ((key))
  #     CLUSTER_NAME: ((cluster))
  #     PROJECT_NAME: ((project))
  #     ZONE: ((zone))

# - name: kubectl
#   plan:
#   - get: knative-test
#   - task: test
#     file: knative-test/ci/tasks/test.yml
#     params:
#       CONFIG: ((key))
#       CLUSTER_NAME: ((cluster))
#       PROJECT_NAME: ((project))
#       ZONE: ((zone))
#     input_mapping: {knative-app: knative-test}

