---
resources:
- name: knative-test
  type: git
  check_every: 10s
  source: {uri: "https://github.com/ddadlani/knative-test"}
- name: helloworld-go
  type: git
  check_every: 10s
  source: {uri: "https://github.com/ddadlani/helloworld-go"}
- name: kubectl
  type: docker-image
  source: {repository: ddadlani/kubectl}

jobs:
- name: unit
  plan:
  - get: knative-test
  - get: helloworld-go
    trigger: true
  - task: test-unit
    file: knative-test/ci/tasks/test-unit.yml

- name: knative-unit
  plan:
  - get: knative-test
    trigger: true
  - get: kubectl
  - task: knative-test-unit
    file: knative-test/ci/tasks/knative-unit.yml
    image: kubectl
    params:
      CONFIG: ((key))
      CLUSTER_NAME: ((cluster))
      PROJECT_NAME: ((project))
      ZONE: ((zone))

- name: build-image
  serial: true
  plan:
  - get: knative-test
    trigger: true
  - get: helloworld-go
    passed: [unit]
    trigger: true
  - get: kubectl
  - task: build-image
    image: kubectl
    file: knative-test/ci/tasks/build-kaniko-image.yml
    params:
      CONFIG: ((key))
      CLUSTER_NAME: ((cluster))
      PROJECT_NAME: ((project))
      ZONE: ((zone))
    input_mapping:
      app: helloworld-go
    timeout: 10m
    on_success:
      task: delete-build
      image: kubectl
      file: knative-test/ci/tasks/delete-build.yml
      params:
        CONFIG: ((key))
        CLUSTER_NAME: ((cluster))
        PROJECT_NAME: ((project))
        ZONE: ((zone))
  # - task: delete-build
  #   image: kubectl
  #   file: knative-test/ci/tasks/delete-build.yml

- name: serve
  serial: true
  plan:
  - get: knative-test
    trigger: true
  - get: helloworld-go
    passed: [unit]
    trigger: true
  - get: kubectl
  - task: serve-hello
    file: knative-test/ci/tasks/serve.yml
    params:
      CONFIG: ((key))
      CLUSTER_NAME: ((cluster))
      PROJECT_NAME: ((project))
      ZONE: ((zone))
