---
resources:
- name: knative-deployment
  type: git
  check_every: 10s
  source: {uri: "https://github.com/ddadlani/concourse-knative-sample"}
- name: helloworld-go
  type: git
  check_every: 10s
  source: {uri: "https://github.com/ddadlani/helloworld-go"}
- name: kubectl
  type: docker-image
  source: {repository: ddadlani/kubectl}

jobs:
- name: test-suite-unit
  plan:
  - get: knative-deployment
    trigger: true
  - get: helloworld-go
    trigger: true
  - task: test-unit
    file: knative-deployment/ci/tasks/test-unit.yml

- name: test-suite-integration
  plan:
  - get: knative-deployment
    trigger: true
  - get: helloworld-go
    trigger: true
  - get: kubectl
  - task: knative-unit-test
    file: knative-deployment/ci/tasks/run-build.yml
    image: kubectl
    params:
      CONFIG: ((key))
      CLUSTER_NAME: ((cluster))
      PROJECT_NAME: ((project))
      ZONE: ((zone))
      BUILD_NAME: go-unit-test
    ensure: delete-build
      image: kubectl
      file: knative-deployment/ci/tasks/delete-build.yml
      params:
        CONFIG: ((key))
        CLUSTER_NAME: ((cluster))
        PROJECT_NAME: ((project))
        ZONE: ((zone))
        BUILD_NAME: go-unit-test

- name: build-image
  serial: true
  plan:
  - get: knative-deployment
    trigger: true
    passed: [test-suite-unit, test-suite-integration]
  - get: helloworld-go
    passed: [test-suite-unit, test-suite-integration]
    trigger: true
  - get: kubectl
  - task: build-image
    image: kubectl
    file: knative-deployment/ci/tasks/run-build.yml
    params:
      CONFIG: ((key))
      CLUSTER_NAME: ((cluster))
      PROJECT_NAME: ((project))
      ZONE: ((zone))
      BUILD_NAME: kaniko-build
    input_mapping:
      app: helloworld-go
    timeout: 10m
    ensure:
      task: delete-build
      image: kubectl
      file: knative-deployment/ci/tasks/delete-build.yml
      params:
        CONFIG: ((key))
        CLUSTER_NAME: ((cluster))
        PROJECT_NAME: ((project))
        ZONE: ((zone))
        BUILD_NAME: kaniko-build

- name: serve
  serial: true
  plan:
  - get: knative-deployment
    passed: [build-image]
    trigger: true
  - get: helloworld-go
    passed: [build-image]
    trigger: true
  - get: kubectl
  - task: serve-hello
    image: kubectl
    file: knative-deployment/ci/tasks/serve.yml
    params:
      CONFIG: ((key))
      CLUSTER_NAME: ((cluster))
      PROJECT_NAME: ((project))
      ZONE: ((zone))
